language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: test-plugins
      if: type != pull_request
      before_install:
        - npm install -g sfdx-cli yarn
      before_script:
        - echo "$SFDX_AUTH_URL" > /tmp/sfdxurl
        - sfdx force:auth:sfdxurl:store -f /tmp/sfdxurl -a ci-devhub -d
      script:
        - sfdx force:org:create -f config/project-scratch-def.json -a ci-scratch-org -s
        - sfdx plugins:link .
        - npm run test:plugins
      after_script:
        - sfdx force:org:delete --noprompt -u ci-scratch-org
    - stage: release
      if: branch = master
      script:
        - npm install --global semantic-release@15
        - semantic-release
